detection:
  model: "yolov8s-world.pt"
  conf_threshold: 0.25
  iou_threshold: 0.50
  tracker_yaml: "botsort.yaml"
  classes:
    - id: 0
      ro: "persoana cu rucsac"
      en: "person with backpack"
    - id: 1
      ro: "vehicul de pista"
      en: "runway vehicle"
    - id: 2
      ro: "pasare"
      en: "bird"
    - id: 3
      ro: "persoana"
      en: "person"
    - id: 4
      ro: "avion"
      en: "airplane"
